import type { Metadata } from "next";
import { Be_Vietnam_Pro, Roboto_Mono } from "next/font/google";
import { QueryProvider } from "@/providers/QueryProvider";
import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "@/components/ui/sonner";
import { KnowledgeNotesWidget } from "@/components/KnowledgeNotes/KnowledgeNotesWidget";
import { Header } from "@/components/layout/Header";
import { AuthGuard } from "@/components/auth/AuthGuard";
import { FloatingAssistant } from "@/components/layout/FloatingAssistant";
import { UIProvider } from "@/contexts/UIContext";
import "./globals.css";

const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Mine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beVietnamPro.variable} ${robotoMono.variable} antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            <UIProvider>
              <Header />
              <AuthGuard>
                {children}
              </AuthGuard>
              <KnowledgeNotesWidget />
              <FloatingAssistant />
            </UIProvider>
          </AuthProvider>
        </QueryProvider>
        <Toaster 
          position="top-center" 
          toastOptions={{
            className: "bg-blue-50 border-blue-200 text-blue-700",
            style: {
              background: "linear-gradient(to right, #EFF6FF, #DBEAFE)",
              border: "1px solid #BFDBFE",
              color: "#1D4ED8"
            }
          }}
        />
      </body>
    </html>
  );
}
