import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryProvider } from "@/providers/QueryProvider";
import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "@/components/ui/sonner";
import { KnowledgeNotesWidget } from "@/components/KnowledgeNotes/KnowledgeNotesWidget";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            {children}
            <KnowledgeNotesWidget />
          </AuthProvider>
        </QueryProvider>
        <Toaster 
          position="top-center" 
          toastOptions={{
            className: "bg-blue-50 border-blue-200 text-blue-700",
            style: {
              background: "linear-gradient(to right, #EFF6FF, #DBEAFE)",
              border: "1px solid #BFDBFE",
              color: "#1D4ED8"
            }
          }}
        />
      </body>
    </html>
  );
}
